const FETCH_POST_SUCCESS = "FETCH_POSTS_SUCCESS";
const FETCH_POST_REQUEST = "FETCH_POST_REQUEST";
const FETCH_POST_FAIL = "FETCH_POST_FAIL";
export { FETCH_POST_REQUEST, FETCH_POST_SUCCESS, FETCH_POST_FAIL };

// named export // default export
